name: Mosaics
favicon: null
layout_spectrum: 0.12116004806011915
typography_spectrum: 0.12109558563679457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7798854995053262
  lightness: 0.7208670866675675
  saturation: 0.4138903215061873
  rhythmicContrast: 0.01916960976086557
purpose: []
